version: '3'

services:
  django-scrape:
    build: .
    container_name: django-scrape
    command: bash -c 'python3 manage.py runserver 0:8000 && python3 manage.py migrate'
    ports:
      - '8000:8000'
    volumes:
      - ~/folder/olx_scraping:/code
    depends_on:
      - celery
  celery:
    build: .
    container_name: celery
    command: bash -c 'celery -A scrape worker -l info'
    volumes:
      - ~/folder/olx_scraping:/code
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3.7
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - '5672:5672'
