# Generated by Django 2.2 on 2019-06-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OlxRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Url for analis')),
                ('email', models.EmailField(max_length=254, verbose_name='Yor email')),
                ('datetime_add_request', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
