# Generated by Django 2.2 on 2019-06-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0002_olxlinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olxrequest',
            name='url',
            field=models.URLField(max_length=2000, verbose_name='Url for analis'),
        ),
    ]
