# Generated by Django 2.2 on 2019-06-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0003_auto_20190617_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='olxlinks',
            name='datetime',
            field=models.DateTimeField(default='2000-01-01 00:01'),
            preserve_default=False,
        ),
    ]
